apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "backend-app.fullname" . }}-route
  annotations:
    nginx.org/server-snippets: |
      http2_max_requests 1;
spec:
  parentRefs:
    - name: shared-gateway
      namespace: monitoring
  hostnames:
    - {{ .Values.hostname | quote }}
  rules:
    - backendRefs:
        - name: {{ include "backend-app.fullname" . }}
          port: {{ .Values.service.port }}