apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-job-viewer-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-job-viewer-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-service-account
roleRef:
  kind: Role
  name: {{ .Release.Name }}-job-viewer-role
  apiGroup: rbac.authorization.k8s.io
