apiVersion: v2
name: my-stack
description: A Helm chart for my Kubernetes frontend application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "18.3.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled