name: Build and Update Manifest
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image for frontend
        run: |
          TAG=${{ github.sha }}
          docker build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/learn-k8s-frontend:$TAG ./frontend
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/learn-k8s-frontend:$TAG
      - name: Build Docker image for backend
        run: |
          TAG=${{ github.sha }}
          docker build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/learn-k8s-backend:$TAG ./backend
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/learn-k8s-backend:$TAG
      - name: Checkout Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/learn-k8s
          token: ${{ secrets.PAT_FOR_MANIFEST_REPO }}
          path: manifest
      - name: Update manifest with new image tags
        run: |
          TAG=${{ github.sha }}
          cd manifest/overlays/production
          kustomize edit set image my-backend-app=ghcr.io/${{ github.repository_owner }}/learn-k8s-backend:$TAG
          kustomize edit set image my-vite-app=ghcr.io/${{ github.repository_owner }}/learn-k8s-frontend:$TAG
      - name: Commit and Push
        run: |
          cd manifest
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy: Update image to ${{ github.sha }}"
          git push
